[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]
; Advanced Binary Compression (Reduces binary size significantly)
bEnableAdvancedBinaryCompression=True
; Use Oodle to shrink the 45+ vehicle textures/data
bUseOodleDataCompression=True
bUseOodleTextureCompression=True
; Loads .so files directly from APK to save RAM install space
bExtractNativeLibs=False
; Minimum SDK 23 for modern Android optimization
MinSDKVersion=23
TargetSDKVersion=34

[/Script/Engine.RendererSettings]
; Forward shading uses less GPU/RAM than Deferred on small phones
r.Mobile.ForwardShading=True
; Helps prevent frames from hanging during AI movement
r.Mobile.DisableVertexFog=True
