[ExcludeDebugData]
Targets="Shipping"
bExcludeFromPaks=True
+Files=".../*.pdb"
+Files=".../*.txt"
+Files="Engine/Content/Editor..."

[MobileTextureReduction]
Platforms="Android"
bExcludeFromPaks=True
; Exclude high-res source files not needed in the APK
+Files=".../*_Source.tga"
+Files=".../*_HighRes.png"
