[Android_High DeviceProfile]
+CVars=r.Streaming.PoolSize=600
+CVars=r.MaxMobileResolution=1080

[Android_Low DeviceProfile]
; This is the "Safety" setting for 4GB RAM phones
+CVars=r.Streaming.PoolSize=256
+CVars=r.MobileContentScaleFactor=0.5
; Limits ALL city textures to 512x512 regardless of their original size
+CVars=r.MaxTextureSize=512
